<?php
/**
 * Template Name: Personal Profile
 * Description: Single-page portfolio for Muhammad Waqas.
 */

$github_url   = 'https://github.com/waqaswaseer';
$linkedin_url = 'https://www.linkedin.com/in/muhammad-waqas-dor-net-developer/';
$email_address = 'waqaswaseer45@gmail.com';
$phone_number  = '+923059074804';
$whatsapp_url  = 'https://wa.me/923059074804';
$theme_uri    = get_template_directory_uri();
?>
<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
    <meta charset="<?php bloginfo( 'charset' ); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Portfolio of Muhammad Waqas, a .NET Developer and Full-Stack Web Developer specializing in C#, ASP.NET, SQL Server, Angular, WordPress and WooCommerce.">
    <title>Muhammad Waqas | .NET Developer &amp; Full-Stack Web Developer</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="<?php echo esc_url( $theme_uri . '/css/profile-style.css' ); ?>">
    <?php wp_head(); ?>
</head>
<body <?php body_class(); ?> data-bs-spy="scroll" data-bs-target="#navbar" data-bs-offset="100">
<?php wp_body_open(); ?>

<nav id="navbar" class="navbar navbar-expand-lg navbar-dark sticky-top" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);">
    <div class="container-fluid">
        <a class="navbar-brand fw-bold" href="#home"><i class="fas fa-code"></i> Muhammad Waqas</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto align-items-lg-center">
                <li class="nav-item"><a class="nav-link" href="#home">Home</a></li><li class="nav-item"><a class="nav-link" href="#about">About</a></li><li class="nav-item"><a class="nav-link" href="#skills">Skills</a></li><li class="nav-item"><a class="nav-link" href="#experience">Experience</a></li><li class="nav-item"><a class="nav-link" href="#projects">Projects</a></li><li class="nav-item"><a class="nav-link" href="#education">Education</a></li><li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
                <li class="nav-item ms-lg-2"><a class="btn btn-sm btn-outline-light" href="#contact">Let's Talk</a></li>
            </ul>
        </div>
    </div>
</nav>

<main>
<section id="home" class="hero-section">
    <div class="hero-background"></div><div class="hero-3d-scene" aria-hidden="true"><div class="hero-orb hero-orb-one"></div><div class="hero-orb hero-orb-two"></div><div class="hero-orb hero-orb-three"></div><div class="hero-cube"><span class="cube-face cube-front"></span><span class="cube-face cube-back"></span><span class="cube-face cube-right"></span><span class="cube-face cube-left"></span><span class="cube-face cube-top"></span><span class="cube-face cube-bottom"></span></div><div class="hero-ring"></div></div>
    <div class="container h-100"><div class="row h-100 align-items-center justify-content-center text-center"><div class="col-lg-9"><div class="hero-content" data-aos="fade-up">
        <p class="text-white-50 text-uppercase fw-semibold mb-3">.NET Developer &bull; Full-Stack Web Developer</p>
        <h1 class="display-3 fw-bold mb-4 text-white">Muhammad Waqas</h1>
        <h2 class="h3 mb-4 text-white-50">.NET Developer | Full-Stack Web Developer</h2>
        <p class="lead mb-5 text-white">Building reliable business applications, reporting systems and E-commerce experiences with .NET, C#, SQL Server and modern web technologies.</p>
        <div class="hero-buttons d-flex flex-wrap justify-content-center gap-3"><a href="#projects" class="btn btn-lg btn-primary"><i class="fas fa-briefcase"></i> View My Work</a><a href="#contact" class="btn btn-lg btn-outline-light"><i class="fas fa-envelope"></i> Contact Me</a><a href="<?php echo esc_url( $github_url ); ?>" class="btn btn-lg btn-outline-light" target="_blank" rel="noopener"><i class="fab fa-github"></i> GitHub</a><a href="<?php echo esc_url( $linkedin_url ); ?>" class="btn btn-lg btn-outline-light" target="_blank" rel="noopener"><i class="fab fa-linkedin"></i> LinkedIn</a></div>
    </div></div></div></div>
</section>

<section id="about" class="py-5"><div class="container"><div class="row align-items-center"><div class="col-lg-5 mb-4 mb-lg-0"><div class="about-image"><div class="gradient-box"><img class="profile-photo" src="<?php echo esc_url( $theme_uri . '/assets/images/portfolio/muhammad-waqas.jpg' ); ?>" alt="Muhammad Waqas, .NET Developer and Full-Stack Web Developer"></div></div></div><div class="col-lg-7"><h2 class="section-title">About Me</h2>
    <p class="lead mb-3">.NET and full-stack web developer experienced in business applications, reporting systems and database-driven web solutions.</p>
    <p>My core stack includes C#, ASP.NET, ASP.NET Core, Web APIs, SQL Server, Angular, JavaScript and TypeScript. I work across backend development, database programming, reporting, large datasets and troubleshooting.</p>
    <p class="mb-0">I also develop and customize WordPress and WooCommerce stores using Elementor and WoodMart, with a focus on reliable functionality, performance and clear user experience.</p>
</div></div></div></section>

<section id="skills" class="py-5 bg-light"><div class="container"><h2 class="section-title text-center">Technical Skills</h2><p class="text-center text-muted mb-5">Technologies used across business applications, reporting portals and E-commerce projects.</p><div class="row g-4">
    <div class="col-lg-4 col-md-6"><article class="skill-card"><div class="skill-icon" style="background:linear-gradient(135deg,#667eea,#764ba2)"><i class="fas fa-server"></i></div><h3 class="h4">Backend</h3><ul class="skill-list"><li>C#</li><li>.NET &amp; .NET Core</li><li>ASP.NET / ASP.NET Core / MVC</li><li>ASP.NET Web API &amp; REST APIs</li></ul></article></div>
    <div class="col-lg-4 col-md-6"><article class="skill-card"><div class="skill-icon" style="background:linear-gradient(135deg,#f093fb,#f5576c)"><i class="fas fa-database"></i></div><h3 class="h4">Database</h3><ul class="skill-list"><li>Microsoft SQL Server &amp; T-SQL</li><li>Stored Procedures</li><li>Complex SQL Queries</li><li>Query Optimization &amp; Large Datasets</li></ul></article></div>
    <div class="col-lg-4 col-md-6"><article class="skill-card"><div class="skill-icon" style="background:linear-gradient(135deg,#4facfe,#00f2fe)"><i class="fas fa-layer-group"></i></div><h3 class="h4">Data Access</h3><ul class="skill-list"><li>Entity Framework</li><li>Entity Framework Core</li><li>Dapper</li><li>Database-driven Applications</li></ul></article></div>
    <div class="col-lg-4 col-md-6"><article class="skill-card"><div class="skill-icon" style="background:linear-gradient(135deg,#fa709a,#fee140)"><i class="fas fa-code"></i></div><h3 class="h4">Frontend</h3><ul class="skill-list"><li>Angular &amp; TypeScript</li><li>JavaScript &amp; jQuery</li><li>HTML5 &amp; CSS3</li><li>Bootstrap</li></ul></article></div>
    <div class="col-lg-4 col-md-6"><article class="skill-card"><div class="skill-icon" style="background:linear-gradient(135deg,#667eea,#00f2fe)"><i class="fas fa-chart-column"></i></div><h3 class="h4">Reporting &amp; UI</h3><ul class="skill-list"><li>DevExtreme &amp; DevExpress</li><li>Flexmonster</li><li>EPPlus &amp; Excel Reporting</li><li>Business Reporting Modules</li></ul></article></div>
    <div class="col-lg-4 col-md-6"><article class="skill-card"><div class="skill-icon" style="background:linear-gradient(135deg,#f5576c,#764ba2)"><i class="fab fa-wordpress"></i></div><h3 class="h4">WordPress &amp; E-Commerce</h3><ul class="skill-list"><li>WordPress &amp; WooCommerce</li><li>Elementor &amp; WoodMart</li><li>Theme / Plugin Configuration</li><li>Stripe, PayPal, Cart &amp; Checkout</li></ul></article></div>
</div></div></section>

<section id="experience" class="py-5"><div class="container"><h2 class="section-title text-center">Professional Experience</h2><p class="text-center text-muted mb-5">A progression focused on practical software development and business applications.</p><div class="row"><div class="col-lg-9 mx-auto"><div class="timeline">
    <article class="timeline-item"><div class="timeline-marker" style="background:linear-gradient(135deg,#667eea,#764ba2)"></div><div class="timeline-content"><h3 class="h4">.NET Developer</h3><span class="text-muted">Tharsol Private Limited &mdash; Faisalabad, Pakistan</span><p class="mt-2 mb-0">Developing and maintaining ASP.NET business applications with C#, SQL Server and T-SQL, including backend features, Web Forms, reporting, stored procedures, complex queries, integrations and production issue resolution.</p></div></article>
    <article class="timeline-item"><div class="timeline-marker" style="background:linear-gradient(135deg,#f093fb,#f5576c)"></div><div class="timeline-content"><h3 class="h4">Junior Software Developer</h3><span class="text-muted">NextStep Business Solution</span><p class="mt-2 mb-0">Contributed to .NET and SQL Server web applications, with responsibility for debugging, business requirements and database-driven functionality.</p></div></article>
    <article class="timeline-item"><div class="timeline-marker" style="background:linear-gradient(135deg,#4facfe,#00f2fe)"></div><div class="timeline-content"><h3 class="h4">Software Development Intern</h3><span class="text-muted">UNIAL Solution Private Limited &mdash; Faisalabad, Pakistan</span><p class="mt-2 mb-0">Supported web application development and built foundational practical development experience.</p></div></article>
</div></div></div></div></section>

<section id="projects" class="py-5 bg-light"><div class="container"><h2 class="section-title text-center">Selected Projects</h2><p class="text-center text-muted mb-5">Professional contributions and public work chosen for relevance to my .NET and full-stack development focus.</p><div class="row g-4">
    <div class="col-lg-6"><article class="project-card h-100"><div class="project-image" style="background:linear-gradient(135deg,#667eea,#764ba2)"><i class="fas fa-chart-line fa-3x text-white" aria-hidden="true"></i></div><div class="project-content"><p class="text-uppercase small fw-semibold text-primary mb-2">Business / Reporting Web Application</p><h3 class="h4">MREP Portal</h3><p>MREP is a business-oriented web portal developed to support back-office users with reporting, data processing and business information management.</p><p class="small mb-3"><strong>Contribution:</strong> Backend development, business logic, SQL Server work, stored procedures, complex queries, report development, data filtering, large dataset handling, client-side validation, performance improvement and troubleshooting.</p><div class="project-tags"><span class="badge bg-primary">C#</span><span class="badge bg-primary">ASP.NET</span><span class="badge bg-warning text-dark">SQL Server</span><span class="badge bg-secondary">T-SQL</span><span class="badge bg-info text-dark">DevExtreme</span></div></div></article></div>
    <div class="col-lg-6"><article class="project-card h-100"><div class="project-image"><img src="<?php echo esc_url( $theme_uri . '/assets/images/portfolio/wordpress-ecommerce-store.png' ); ?>" alt="Screenshot of a WordPress E-commerce store displaying bags" loading="lazy"></div><div class="project-content"><p class="text-uppercase small fw-semibold text-primary mb-2">E-Commerce Website</p><h3 class="h4">WordPress E-Commerce Store</h3><p>Developed and customized a WordPress-based E-commerce website focused on online retail products including bags and shoes.</p><p class="small mb-3"><strong>Features:</strong> Product catalog, categories, product detail pages, variations, cart, checkout, customer accounts, order administration, responsive UI and payment configuration.</p><div class="project-tags"><span class="badge bg-primary">WordPress</span><span class="badge bg-success">WooCommerce</span><span class="badge bg-danger">Elementor</span><span class="badge bg-dark">WoodMart</span><span class="badge bg-info text-dark">Stripe / PayPal</span></div><p class="small text-muted mt-3 mb-0">Live website: [ADD LIVE WEBSITE URL]</p></div></article></div>
    <div class="col-lg-6"><article class="project-card h-100"><div class="project-image"><img src="<?php echo esc_url( $theme_uri . '/assets/images/portfolio/minhajlab-angular.jpg' ); ?>" alt="Screenshot of the MinhajLab web interface" loading="lazy"></div><div class="project-content"><p class="text-uppercase small fw-semibold text-primary mb-2">Public GitHub Project</p><h3 class="h4">MinhajLab Angular Application</h3><p>An Angular CLI application published on GitHub, demonstrating a web interface built with Angular, TypeScript, HTML and CSS.</p><p class="small mb-3"><strong>Purpose:</strong> Frontend application work for a laboratory-oriented web interface. Public repository details are kept concise where functionality is not documented.</p><div class="project-tags"><span class="badge bg-danger">Angular</span><span class="badge bg-primary">TypeScript</span><span class="badge bg-secondary">HTML</span><span class="badge bg-info text-dark">CSS</span></div><a href="https://github.com/waqaswaseer/minhajLabA" target="_blank" rel="noopener" class="btn btn-sm btn-outline-primary mt-3"><i class="fab fa-github"></i> Repository</a></div></article></div>
    <div class="col-lg-6"><article class="project-card h-100"><div class="project-image" style="background:linear-gradient(135deg,#f093fb,#f5576c)"><i class="fas fa-user-shield fa-3x text-white" aria-hidden="true"></i></div><div class="project-content"><p class="text-uppercase small fw-semibold text-primary mb-2">Public GitHub Project</p><h3 class="h4">Patient Portal Angular Application</h3><p>An Angular application repository that includes API-oriented functionality and user sign-in and sign-up flows, according to its public project description.</p><p class="small mb-3"><strong>Technologies:</strong> Angular, TypeScript, JavaScript, HTML, CSS and SCSS.</p><div class="project-tags"><span class="badge bg-danger">Angular</span><span class="badge bg-primary">TypeScript</span><span class="badge bg-success">JavaScript</span><span class="badge bg-secondary">HTML / CSS</span></div><a href="https://github.com/waqaswaseer/patientPortalAngularOnly" target="_blank" rel="noopener" class="btn btn-sm btn-outline-primary mt-3"><i class="fab fa-github"></i> Repository</a></div></article></div>
</div><div class="text-center mt-5"><a href="<?php echo esc_url( $github_url ); ?>" class="btn btn-lg btn-primary" target="_blank" rel="noopener"><i class="fab fa-github"></i> Explore GitHub</a></div></div></section>

<section id="services" class="py-5"><div class="container"><h2 class="section-title text-center">What I Can Build</h2><p class="text-center text-muted mb-5">Development services grounded in the technologies and application work represented above.</p><div class="row g-4"><div class="col-md-6 col-lg-4"><article class="cert-card h-100"><div class="cert-icon"><i class="fas fa-laptop-code"></i></div><h3 class="h5">.NET Web Development</h3><p class="mb-0">Custom business applications using C#, ASP.NET and ASP.NET Core.</p></article></div><div class="col-md-6 col-lg-4"><article class="cert-card h-100"><div class="cert-icon"><i class="fas fa-code-branch"></i></div><h3 class="h5">Full-Stack &amp; APIs</h3><p class="mb-0">Frontend and backend components plus REST API development and integration.</p></article></div><div class="col-md-6 col-lg-4"><article class="cert-card h-100"><div class="cert-icon"><i class="fas fa-database"></i></div><h3 class="h5">SQL Server Development</h3><p class="mb-0">Stored procedures, complex queries, database development and query optimization.</p></article></div><div class="col-md-6 col-lg-4"><article class="cert-card h-100"><div class="cert-icon"><i class="fas fa-chart-pie"></i></div><h3 class="h5">Business &amp; Reporting Systems</h3><p class="mb-0">Portals, dashboards, administrative workflows and reporting applications.</p></article></div><div class="col-md-6 col-lg-4"><article class="cert-card h-100"><div class="cert-icon"><i class="fab fa-wordpress"></i></div><h3 class="h5">WordPress Development</h3><p class="mb-0">Professional WordPress website development, customization and maintenance.</p></article></div><div class="col-md-6 col-lg-4"><article class="cert-card h-100"><div class="cert-icon"><i class="fas fa-cart-shopping"></i></div><h3 class="h5">WooCommerce Development</h3><p class="mb-0">E-commerce stores, theme customization, cart and checkout setup, payments and troubleshooting.</p></article></div></div></div></section>

<section id="education" class="py-5 bg-light"><div class="container"><div class="row g-4 justify-content-center"><div class="col-lg-5"><article class="cert-card h-100"><div class="cert-icon"><i class="fas fa-graduation-cap"></i></div><h2 class="h4">Education</h2><h3 class="h5">Bachelor of Science in Software Engineering</h3><p class="text-muted mb-0">University of Agriculture, Faisalabad &bull; 2016 &ndash; 2020</p></article></div><div id="certifications" class="col-lg-5"><article class="cert-card h-100"><div class="cert-icon"><i class="fas fa-certificate"></i></div><h2 class="h4">Certification</h2><h3 class="h5">Artificial Intelligence &amp; Machine Learning Certification</h3><p class="text-muted mb-0">KICS, UET Lahore &bull; 2020</p><p class="small mt-2 mb-0">Academic training listed as additional learning; it is not presented as the focus of my professional practice.</p></article></div></div></div></section>

<section id="contact" class="py-5 bg-light"><div class="container"><h2 class="section-title text-center">Let's Build Something Great</h2><p class="text-center text-muted mb-5">Whether you are looking for a software engineer, need help building a web application, or want to discuss a technical project, feel free to get in touch.</p><div class="row"><div class="col-lg-8 mx-auto">
    <?php if ( isset( $_GET['contact'] ) && 'success' === sanitize_key( wp_unslash( $_GET['contact'] ) ) ) : ?><div class="alert alert-success" role="status">Thanks for your message. It has been sent successfully.</div><?php elseif ( isset( $_GET['contact'] ) && 'error' === sanitize_key( wp_unslash( $_GET['contact'] ) ) ) : ?><div class="alert alert-danger" role="alert">Your message could not be sent. Please try again later.</div><?php endif; ?>
    <div class="row g-4 mb-5"><div class="col-12 col-sm-6 col-lg-4 text-center"><div class="contact-info-box"><div class="contact-icon" style="background:linear-gradient(135deg,#667eea,#764ba2)"><i class="fas fa-envelope"></i></div><h3 class="h5">Email</h3><p class="mb-0"><a href="mailto:<?php echo esc_attr( $email_address ); ?>"><?php echo esc_html( $email_address ); ?></a></p></div></div><div class="col-12 col-sm-6 col-lg-4 text-center"><div class="contact-info-box"><div class="contact-icon" style="background:linear-gradient(135deg,#f093fb,#f5576c)"><i class="fas fa-phone"></i></div><h3 class="h5">Phone</h3><p class="mb-0"><a href="tel:<?php echo esc_attr( $phone_number ); ?>"><?php echo esc_html( $phone_number ); ?></a></p></div></div><div class="col-12 col-sm-6 col-lg-4 text-center"><div class="contact-info-box"><div class="contact-icon" style="background:linear-gradient(135deg,#25d366,#128c7e)"><i class="fab fa-whatsapp"></i></div><h3 class="h5">WhatsApp</h3><p class="mb-0"><a href="<?php echo esc_url( $whatsapp_url ); ?>" target="_blank" rel="noopener">Preferred direct contact</a></p></div></div><div class="col-12 col-sm-6 col-lg-4 text-center"><div class="contact-info-box"><div class="contact-icon" style="background:linear-gradient(135deg,#4facfe,#00f2fe)"><i class="fas fa-map-marker-alt"></i></div><h3 class="h5">Location</h3><p class="mb-0">Pakistan</p></div></div><div class="col-12 col-sm-6 col-lg-4 text-center"><div class="contact-info-box"><div class="contact-icon" style="background:linear-gradient(135deg,#fa709a,#fee140)"><i class="fab fa-linkedin"></i></div><h3 class="h5">LinkedIn</h3><p class="mb-0"><a href="<?php echo esc_url( $linkedin_url ); ?>" target="_blank" rel="noopener">Connect</a></p></div></div></div>
    <div class="contact-form-box"><h3 class="h4 mb-4">Send me a Message</h3><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="waqasprofile_contact"><input type="hidden" name="redirect_to" value="<?php echo esc_url( get_permalink() . '#contact' ); ?>"><?php wp_nonce_field( 'waqasprofile_contact', 'waqasprofile_nonce' ); ?><div class="visually-hidden" aria-hidden="true"><label for="website">Website</label><input id="website" type="text" name="website" tabindex="-1" autocomplete="off"></div><div class="row g-3"><div class="col-md-6"><label class="visually-hidden" for="contact-name">Name</label><input id="contact-name" type="text" class="form-control" placeholder="Your Name" name="contact_name" required></div><div class="col-md-6"><label class="visually-hidden" for="contact-email">Email</label><input id="contact-email" type="email" class="form-control" placeholder="Your Email" name="contact_email" required></div><div class="col-12"><label class="visually-hidden" for="contact-subject">Subject</label><input id="contact-subject" type="text" class="form-control" placeholder="Subject" name="contact_subject" required></div><div class="col-12"><label class="visually-hidden" for="contact-message">Message</label><textarea id="contact-message" class="form-control" rows="5" placeholder="Your Message" name="contact_message" required></textarea></div><div class="col-12"><button type="submit" class="btn btn-lg btn-primary w-100"><i class="fas fa-paper-plane"></i> Send Message</button></div></div></form></div>
    <div class="social-links text-center mt-5"><h3 class="h5 mb-4">Connect With Me</h3><div class="social-icons"><a href="<?php echo esc_url( $linkedin_url ); ?>" target="_blank" rel="noopener" class="social-icon" aria-label="LinkedIn profile"><i class="fab fa-linkedin"></i></a><a href="<?php echo esc_url( $github_url ); ?>" target="_blank" rel="noopener" class="social-icon" aria-label="GitHub profile"><i class="fab fa-github"></i></a></div></div>
</div></div></div></section>
</main>

<footer class="bg-dark text-white py-4"><div class="container text-center"><p class="mb-2"><strong>Muhammad Waqas</strong> &mdash; .NET Developer | Full-Stack Web Developer</p><p class="mb-2"><a class="text-white-50 me-3" href="<?php echo esc_url( $github_url ); ?>" target="_blank" rel="noopener">GitHub</a><a class="text-white-50" href="<?php echo esc_url( $linkedin_url ); ?>" target="_blank" rel="noopener">LinkedIn</a></p><p class="mb-0">&copy; <?php echo esc_html( wp_date( 'Y' ) ); ?> Muhammad Waqas. Built with modern web technologies.</p></div></footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script>
document.querySelectorAll('a[href^="#"]').forEach(anchor => { anchor.addEventListener('click', function (event) { const target = document.querySelector(this.getAttribute('href')); if (target) { event.preventDefault(); target.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth' }); } }); });
document.querySelectorAll('#navbarNav .nav-link').forEach(link => link.addEventListener('click', () => { const menu = document.querySelector('#navbarNav'); const instance = bootstrap.Collapse.getInstance(menu); if (instance) instance.hide(); }));
const navbar = document.querySelector('#navbar');
if (navbar && window.bootstrap) {
    new bootstrap.ScrollSpy(document.body, {
        target: '#navbar',
        offset: 100
    });
}
const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) entry.target.classList.add('animate-in'); }), { threshold: .1, rootMargin: '0px 0px -100px 0px' });
document.querySelectorAll('.skill-card, .project-card, .cert-card, .timeline-content, .contact-info-box').forEach((element, index) => { element.classList.add('reveal-3d'); element.style.setProperty('--reveal-delay', `${(index % 3) * 90}ms`); observer.observe(element); });
if (window.matchMedia('(hover: hover) and (pointer: fine)').matches && !window.matchMedia('(prefers-reduced-motion: reduce)').matches) { document.querySelectorAll('.skill-card, .project-card, .cert-card, .timeline-content, .contact-info-box').forEach(card => { card.classList.add('tilt-card'); card.addEventListener('pointermove', event => { const bounds = card.getBoundingClientRect(), x = (event.clientX - bounds.left) / bounds.width - .5, y = (event.clientY - bounds.top) / bounds.height - .5; card.style.setProperty('--tilt-x', `${(y * -7).toFixed(2)}deg`); card.style.setProperty('--tilt-y', `${(x * 7).toFixed(2)}deg`); }); card.addEventListener('pointerleave', () => { card.style.removeProperty('--tilt-x'); card.style.removeProperty('--tilt-y'); }); }); }
</script>
<?php wp_footer(); ?>
</body>
</html>
